version: '3'
services:
  web:
    depends_on:
      - php
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
  php:
    depends_on:
      - mysql
    build: ./php-backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWD=$DB_USER_PASSWORD
    volumes:
      - ./app:/app
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PASSWORD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
   

# services:
#   database:
#     build: ./mysql-db
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
#       - MYSQL_DATABASE=$DB_NAME
#       - MYSQL_USER=$DB_USER
#       - MYSQL_PASSWORD=$DB_USER_PASSWORD
#     volumes:
#       - db:/var/lib/mysql
#   backend:
#     depends_on:
#       - database
#     build: ./php-backend
#     restart: unless-stopped
#     env_file: ./.env
#     ports:
#       - $PHP_PORT:3000
#     environment:
#       - DB_HOST=database
#       - DB_PORT=3306
#       - DB_NAME=$DB_NAME
#       - DB_USER=$DB_USER
#       - DB_PASSWD=$DB_USER_PASSWORD
#       - PORT=$PHP_PORT
#     volumes:
#       - ./php-backend:/app

# volumes:
#   db:
#   node_modules:
